# Generated by Django 5.2.9 on 2025-12-14 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PRDDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numero da versao do documento",
                        verbose_name="versao",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Conteudo do PRD em formato Markdown",
                        verbose_name="conteudo",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Resumo breve do PRD",
                        verbose_name="resumo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("pending_review", "Aguardando Revisao"),
                            ("revision_requested", "Revisao Solicitada"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Status atual do documento",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Se esta versao foi aprovada pelo usuario",
                        verbose_name="aprovado",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da aprovacao",
                        null=True,
                        verbose_name="aprovado em",
                    ),
                ),
                (
                    "change_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descricao das alteracoes em relacao a versao anterior",
                        verbose_name="notas de alteracao",
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numero de palavras no documento",
                        verbose_name="contagem de palavras",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que aprovou o documento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_prd_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aprovado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que solicitou esta versao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prd_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia a versao anterior do documento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="documents.prddocument",
                        verbose_name="versao anterior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento PRD",
                "verbose_name_plural": "Documentos PRD",
                "db_table": "documents_prd",
                "ordering": ["-version", "-created_at"],
            },
        ),
    ]
