# Generated by Django 5.2.9 on 2025-12-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prddocument",
            name="problem",
            field=models.ForeignKey(
                help_text="Problema ao qual este PRD pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prd_documents",
                to="problems.problem",
                verbose_name="problema",
            ),
        ),
        migrations.AddIndex(
            model_name="prddocument",
            index=models.Index(
                fields=["problem", "version"], name="documents_p_problem_8ef95f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prddocument",
            index=models.Index(
                fields=["problem", "status"], name="documents_p_problem_4de366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prddocument",
            index=models.Index(
                fields=["problem", "is_approved"], name="documents_p_problem_7c4481_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prddocument",
            constraint=models.UniqueConstraint(
                fields=("problem", "version"), name="unique_prd_version_per_problem"
            ),
        ),
    ]
