# Generated by Django 5.2.9 on 2025-12-14 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechSpecDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numero da versao do documento",
                        verbose_name="versao",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Conteudo da especificacao tecnica em formato Markdown",
                        verbose_name="conteudo",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Resumo breve da especificacao tecnica",
                        verbose_name="resumo",
                    ),
                ),
                (
                    "architecture_overview",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descricao de alto nivel da arquitetura proposta",
                        verbose_name="visao geral da arquitetura",
                    ),
                ),
                (
                    "estimated_complexity",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("very_high", "Muito Alta"),
                        ],
                        default="medium",
                        help_text="Nivel de complexidade estimado para implementacao",
                        max_length=10,
                        verbose_name="complexidade estimada",
                    ),
                ),
                (
                    "estimated_tasks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numero estimado de tarefas para implementacao",
                        verbose_name="tarefas estimadas",
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de tecnologias e bibliotecas recomendadas",
                        verbose_name="tecnologias",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("pending_review", "Aguardando Revisao"),
                            ("revision_requested", "Revisao Solicitada"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Status atual do documento",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Se esta versao foi aprovada pelo usuario",
                        verbose_name="aprovado",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da aprovacao",
                        null=True,
                        verbose_name="aprovado em",
                    ),
                ),
                (
                    "change_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descricao das alteracoes em relacao a versao anterior",
                        verbose_name="notas de alteracao",
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numero de palavras no documento",
                        verbose_name="contagem de palavras",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que aprovou o documento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tech_spec_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aprovado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que solicitou esta versao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tech_spec_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia a versao anterior do documento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="documents.techspecdocument",
                        verbose_name="versao anterior",
                    ),
                ),
                (
                    "prd_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="PRD no qual esta especificacao tecnica se baseia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tech_specs",
                        to="documents.prddocument",
                        verbose_name="documento PRD",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="Problema ao qual esta especificacao tecnica pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_spec_documents",
                        to="problems.problem",
                        verbose_name="problema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especificacao Tecnica",
                "verbose_name_plural": "Especificacoes Tecnicas",
                "db_table": "documents_tech_spec",
                "ordering": ["-version", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["problem", "version"],
                        name="documents_t_problem_ea7dd1_idx",
                    ),
                    models.Index(
                        fields=["problem", "status"],
                        name="documents_t_problem_ebf2fa_idx",
                    ),
                    models.Index(
                        fields=["problem", "is_approved"],
                        name="documents_t_problem_52f5d7_idx",
                    ),
                    models.Index(
                        fields=["prd_document", "version"],
                        name="documents_t_prd_doc_d89a2d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("problem", "version"),
                        name="unique_tech_spec_version_per_problem",
                    )
                ],
            },
        ),
    ]
