# Generated by Django 5.2.9 on 2025-12-14 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titulo breve descrevendo o problema",
                        max_length=255,
                        verbose_name="titulo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descricao detalhada do problema ou feature",
                        verbose_name="descricao",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("analyzing", "Analisando"),
                            ("prd_generation", "Gerando PRD"),
                            ("prd_review", "Revisao de PRD"),
                            ("spec_generation", "Gerando Especificacao"),
                            ("spec_review", "Revisao de Especificacao"),
                            ("task_creation", "Criando Tarefas"),
                            ("task_selection", "Selecao de Tarefas"),
                            ("executing", "Executando"),
                            ("testing", "Testando"),
                            ("completed", "Concluido"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Status atual do workflow",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Critica"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Nivel de prioridade do problema",
                        max_length=10,
                        verbose_name="prioridade",
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID do workflow Celery associado",
                        max_length=255,
                        verbose_name="ID do workflow",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Mensagem de erro se o status for "failed"',
                        verbose_name="mensagem de erro",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que criou o problema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organizacao a qual este problema pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="organizations.organization",
                        verbose_name="organizacao",
                    ),
                ),
                (
                    "repositories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Repositorios envolvidos na solucao deste problema",
                        related_name="problems",
                        to="organizations.repository",
                        verbose_name="repositorios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problema",
                "verbose_name_plural": "Problemas",
                "db_table": "problems_problem",
                "ordering": ["-created_at", "priority"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="problems_pr_organiz_93e3a0_idx",
                    ),
                    models.Index(
                        fields=["organization", "priority"],
                        name="problems_pr_organiz_b6f95b_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="problems_pr_created_0d5ff9_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="problems_pr_status_bae5fe_idx",
                    ),
                ],
            },
        ),
    ]
