# Generated by Django 5.2.9 on 2025-12-14 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0003_techspecdocument"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titulo breve descrevendo a tarefa",
                        max_length=500,
                        verbose_name="titulo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descricao detalhada do que precisa ser feito",
                        verbose_name="descricao",
                    ),
                ),
                (
                    "spec",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Especificacao detalhada para implementacao da tarefa",
                        verbose_name="especificacao",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ordem de execucao da tarefa",
                        verbose_name="ordem",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("selected", "Selecionado"),
                            ("in_progress", "Em Progresso"),
                            ("testing", "Testando"),
                            ("completed", "Concluido"),
                            ("failed", "Falhou"),
                            ("skipped", "Pulado"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status atual da tarefa",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Critica"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Nivel de prioridade da tarefa",
                        max_length=10,
                        verbose_name="prioridade",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature"),
                            ("bugfix", "Bugfix"),
                            ("refactor", "Refatoracao"),
                            ("test", "Teste"),
                            ("documentation", "Documentacao"),
                            ("config", "Configuracao"),
                        ],
                        default="feature",
                        help_text="Tipo da tarefa",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "implementation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detalhes da implementacao em formato JSON",
                        verbose_name="implementacao",
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Resultados dos testes em formato JSON",
                        verbose_name="resultados de teste",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de inicio da execucao",
                        null=True,
                        verbose_name="iniciado em",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de conclusao",
                        null=True,
                        verbose_name="concluido em",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Mensagem de erro se a tarefa falhou",
                        verbose_name="mensagem de erro",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nome da branch Git para as alteracoes desta tarefa",
                        max_length=255,
                        verbose_name="nome da branch",
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA do commit Git com as alteracoes",
                        max_length=40,
                        verbose_name="SHA do commit",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tempo estimado em horas para completar a tarefa",
                        max_digits=5,
                        null=True,
                        verbose_name="horas estimadas",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tempo real gasto em horas",
                        max_digits=5,
                        null=True,
                        verbose_name="horas reais",
                    ),
                ),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tarefas que devem ser concluidas antes desta",
                        related_name="dependent_tasks",
                        to="tasks_app.task",
                        verbose_name="dependencias",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="Problema ao qual esta tarefa pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="problems.problem",
                        verbose_name="problema",
                    ),
                ),
                (
                    "tech_spec",
                    models.ForeignKey(
                        blank=True,
                        help_text="Especificacao tecnica da qual esta tarefa foi gerada",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="documents.techspecdocument",
                        verbose_name="especificacao tecnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "db_table": "tasks_task",
                "ordering": ["order_index", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["problem", "status"],
                        name="tasks_task_problem_2e1258_idx",
                    ),
                    models.Index(
                        fields=["problem", "order_index"],
                        name="tasks_task_problem_6e4f99_idx",
                    ),
                    models.Index(
                        fields=["tech_spec", "status"],
                        name="tasks_task_tech_sp_e019fd_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="tasks_task_status_01b536_idx",
                    ),
                ],
            },
        ),
    ]
