# Generated by Django 5.2.9 on 2025-12-14 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Executando"),
                            ("completed", "Concluido"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                            ("timeout", "Tempo Esgotado"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status atual desta execucao",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de inicio da execucao",
                        null=True,
                        verbose_name="iniciado em",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de conclusao da execucao",
                        null=True,
                        verbose_name="concluido em",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("code_writer", "Code Writer Agent"),
                            ("test_runner", "Test Runner Agent"),
                            ("business_analyst", "Business Analyst Agent"),
                            ("tech_architect", "Tech Architect Agent"),
                            ("task_planner", "Task Planner Agent"),
                            ("unknown", "Desconhecido"),
                        ],
                        default="unknown",
                        help_text="Tipo de agente que executou a tarefa",
                        max_length=50,
                        verbose_name="tipo de agente",
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Logs detalhados da execucao",
                        verbose_name="logs",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Saida/resultados da execucao",
                        verbose_name="saida",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detalhes do erro se a execucao falhou",
                        verbose_name="mensagem de erro",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metricas de performance em formato JSON",
                        verbose_name="metricas",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numero da tentativa (para retries)",
                        verbose_name="numero da tentativa",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID da tarefa Celery que esta executando",
                        max_length=255,
                        verbose_name="ID da tarefa Celery",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Tarefa sendo executada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tasks_app.task",
                        verbose_name="tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execucao de Tarefa",
                "verbose_name_plural": "Execucoes de Tarefas",
                "db_table": "tasks_execution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "status"], name="tasks_execu_task_id_3af754_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="tasks_execu_status_7a3337_idx",
                    ),
                    models.Index(
                        fields=["agent_type", "status"],
                        name="tasks_execu_agent_t_c7002c_idx",
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="tasks_execu_celery__09ca5a_idx"
                    ),
                ],
            },
        ),
    ]
