# Generated by Django 5.2.9 on 2025-12-14 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da organizacao",
                        max_length=255,
                        verbose_name="nome",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador unico para URLs",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descricao da organizacao",
                        verbose_name="descricao",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL para o logo da organizacao",
                        verbose_name="URL do logo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se a organizacao esta ativa",
                        verbose_name="ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizacao",
                "verbose_name_plural": "Organizacoes",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="organizatio_slug_048085_idx"),
                    models.Index(
                        fields=["is_active"], name="organizatio_is_acti_1ffc28_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("member", "Membro"),
                            ("viewer", "Visualizador"),
                        ],
                        default="member",
                        help_text="Papel do membro na organizacao",
                        max_length=20,
                        verbose_name="papel",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data em que o usuario entrou na organizacao",
                        verbose_name="data de entrada",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="convidado por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.organization",
                        verbose_name="organizacao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Organizacao",
                "verbose_name_plural": "Membros da Organizacao",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "user"],
                        name="organizatio_organiz_493f43_idx",
                    ),
                    models.Index(fields=["role"], name="organizatio_role_5b8148_idx"),
                ],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do repositorio",
                        max_length=255,
                        verbose_name="nome",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL completa do repositorio (ex: https://github.com/org/repo)",
                        max_length=500,
                        verbose_name="URL do repositorio",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                        ],
                        default="github",
                        help_text="Provedor do repositorio",
                        max_length=20,
                        verbose_name="provedor",
                    ),
                ),
                (
                    "default_branch",
                    models.CharField(
                        default="main",
                        help_text="Nome da branch principal",
                        max_length=100,
                        verbose_name="branch padrao",
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Token de acesso para repositorios privados (criptografado)",
                        max_length=500,
                        verbose_name="token de autenticacao",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Se o repositorio e privado",
                        verbose_name="privado",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data da ultima sincronizacao do repositorio",
                        null=True,
                        verbose_name="ultima sincronizacao",
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Caminho local onde o repositorio foi clonado",
                        max_length=500,
                        verbose_name="caminho local",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="organizations.organization",
                        verbose_name="organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repositorio",
                "verbose_name_plural": "Repositorios",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="organizatio_organiz_a93050_idx",
                    ),
                    models.Index(
                        fields=["provider"], name="organizatio_provide_4576be_idx"
                    ),
                ],
                "unique_together": {("organization", "url")},
            },
        ),
    ]
