# Generated by Django 5.2.9 on 2025-12-14 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e hora de criacao do registro",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Data e hora da ultima atualizacao do registro",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("user", "Usuario"), ("agent", "Agente")],
                        db_index=True,
                        help_text="Tipo de remetente da mensagem (usuario ou agente)",
                        max_length=10,
                        verbose_name="tipo de remetente",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business_analyst", "Business Analyst"),
                            ("tech_architect", "Tech Architect"),
                            ("task_planner", "Task Planner"),
                            ("code_writer", "Code Writer"),
                            ("test_runner", "Test Runner"),
                        ],
                        default="",
                        help_text="Nome do agente que enviou a mensagem (se sender_type for agent)",
                        max_length=50,
                        verbose_name="nome do agente",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Conteudo da mensagem", verbose_name="conteudo"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("question", "Pergunta"),
                            ("answer", "Resposta"),
                            ("info", "Informacao"),
                            ("error", "Erro"),
                            ("system", "Sistema"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Tipo da mensagem",
                        max_length=20,
                        verbose_name="tipo de mensagem",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais em formato JSON",
                        verbose_name="metadados",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a mensagem foi lida",
                        verbose_name="lida",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="Problema ao qual esta mensagem esta associada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="problems.problem",
                        verbose_name="problema",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que enviou a mensagem (se sender_type for user)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Chat",
                "verbose_name_plural": "Mensagens de Chat",
                "db_table": "chat_chatmessage",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["problem", "created_at"],
                        name="chat_chatme_problem_59117a_idx",
                    ),
                    models.Index(
                        fields=["problem", "sender_type"],
                        name="chat_chatme_problem_b52f1a_idx",
                    ),
                    models.Index(
                        fields=["sender_user", "created_at"],
                        name="chat_chatme_sender__4fc78e_idx",
                    ),
                ],
            },
        ),
    ]
